### ISSUE TITLE
Why public/* ?

### ISSUE THREAD

**Issue by matteodem** [numtel/meteor-publicsources#1]
Really great idea and surely a helpful package for bigger apps! But I thought it'd be really cool if it's possible to define the templates like in current apps (in client folders) and then have logic that only loads the templates that you specified when the route is being loaded. As an example:

``` javascript
Router.route('/', function () {
  this.render('hello');
  // hello.html is somewhere in client/*
  this.loadTemplates('hello', ...);
}, {
  controller: 'PreloadController',
  preload: {
    styles: 'hello.css',
    sync: 'hello.js'
  }
});
```

The templates would still be autoloaded by Meteor but we could control what gets sent down to the client. I didn't dig into the core yet but I think, hope that this is possible. 

wdyt?

**Comment by numtel** [comment]
Good question. I did try to make something like this happen but ran into a snag.

I found it was possible to patch Meteor so that certain files in `client` are not included (while in `development` mode) but when switching to `production` with minified resources, I could not figure out a way to exclude said resources from being minified due to the necessary build functions and objects not being exposed.

I guess a question for you: is there some reason that including the templates inside of the publicsource bundle does not work?

**Comment by jadsonlourenco** [comment]
Hi @numtel thank you for you reply on https://github.com/MeteorCommunity/discussions/issues/27#issuecomment-70912504

I understand this package, and make it work for me, but this question is good because we use "client" folder to save our templates files. But if put on "client" folder not works, like you said now, Meteor will compile all templates like bundle, part of app code, not like an asset.

But my question is just to know how I can do this method, to use this package with "{{template}}" include? I need add all templates on "publicsource.json" and then how I do that?

Other thing: if the templates are on "public" folder so will be public for anyone access this using a direct link? So is better use "private" folder?

Sorry about that, you make an amazing job with this package and thinking but I need to know how use in others cases, like for mobile app if it works better then use default way.

**Comment by numtel** [comment]
I'm not 100% sure what you're asking but I think this should help:

If you place `.html` files with templates inside a bundle in the `publicsource.json` file, they get converted into Javascript which will be loaded along with the rest of the javascript files listed in the bundle.

`.html` files are automatically sorted to the beginning of the bundle to ensure that the templates are ready for helpers and event handlers so if you're using a different template filetype (like `.jade`), make sure that the template files are included first in the bundle. E.g.:

```
{
  "some-bundle": [ "my-feature.jade", "my-feature.js" ]
}
```

Then browse to `http://localhost:3000/some-bundle.js` (adjust for your Meteor app url) and see the Blaze template will be included before the other scripts.

It was pretty late when I published the package last night, I'm definitely going to update the readme soon with more information about use-cases.

---

As for the security of templates being located in the `public` directory or made public in a bundle: yes, the code will be available to any client with no restrictions.

I am still thinking about how to go about providing `allow()`/`deny()` rules on lazy-loaded bundles.

**Comment by jadsonlourenco** [comment]
For rules using Iron-router I use that: https://atmospherejs.com/zimme/iron-router-auth
But my questions is about using **spacebars** with this method, for example, in Iron Router we can define global vars like that:

```
Router.configure({
    layoutTemplate: 'main',
    notFoundTemplate: 'notFound',
    loadingTemplate: 'loading'
});
```

in this case Iron Router not get the template "main" if I put this on "public" folder, you know?

**Comment by numtel** [comment]
That `iron-router-auth` package will not stop anybody from loading the bundle script contents manually though if you're trying to secure templates.

If you had a layout template `main` with an include of a lazy-loaded template `{{>someLazyTemplate }}`, I would think that you would need a helper function with a conditional wrapping it to determine whether to include the template, something like: `{{#if lazyTemplateLoaded}}`

**Comment by matteodem** [comment]
Can we please keep this to the original topic of the issue and create new one's for other issues?

Yes, it surely does work like it is right now. But I don't think that we want to extend the loading of templates, but rather replace the current functionality in the long term. I dont see the need to include the templates automatically in the client anymore when you have huge apps which only should load the lowest amount of resources possible. I fully understand it though if that's not what you had in mind.

**Comment by numtel** [comment]
I'm not exactly sure what the issue is. Am I understanding correctly when I say, you want to completely replace how Meteor loads files from the app directory so that **NO** templates are loaded automatically?

It is definitely not the intention of this package to do this and I'm not sure why such a dramatic change would be necessary.

**Comment by matteodem** [comment]
Yes, only on the client though. Just to me it seems like a bigger task to put all templates to a public folder from an existing "huge" app and adding all that configuration. Also this package makes the templates publicly available to everyone (not different from now), overriding the logic could prevent that. I think the core team is having an eye on that and if this feature is not what your package is meant for, than there's nothing to discuss. I'm sure thought that it'll be helpful to a lot of people in the community, thanks.

**Comment by numtel** [comment]
@matteodem 

So  in your example posted at the start of the thread, you're picturing a situation where the templates would all be loaded on the server?

Otherwise, there would be no way to have a statement such as:

```
  // hello.html is somewhere in client/*
  this.loadTemplates('hello', ...);
```

As the `Template.hello.events`, helpers, rendered... code would cause errors if the template was missing.

**Comment by matteodem** [comment]
it would also require to have javascript files and css being loaded.

``` javascript
Router.route('/', function () {
  this.render('hello');
  this.loadTemplates('hello.html'); 
  this.loadJs('hello.js');
  this.loadCss('hello.less');

  // OR 
  this.load('hello.html', 'hello.js', 'hello.less');
});
```

Of course there needs to be more consideration and thoughts being put into it, but I imagine only modifying the logic of the client side loading of resources and some route specific, global configuration that tells you which packages, or whatever to include on every route.

This task is huge and I'm pretty sure that the core is on it and they surely know how to handle that the best :smile:
